In [1]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 76.6 MB 1.2 MB/s 


In [2]:
import re
import pandas as pd
from sklearn.svm import SVC
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
import keras
from sklearn.metrics import classification_report,confusion_matrix
import nltk
import matplotlib.pyplot as plt
from sklearn.model_selection import (train_test_split,cross_val_predict,
                                     cross_val_score,cross_validate,GridSearchCV,StratifiedKFold
                                    )
from sklearn import ensemble, linear_model,svm,neighbors,neural_network
from sklearn.metrics import (classification_report,confusion_matrix,
                             accuracy_score,auc,mean_absolute_error,r2_score,mean_squared_error,
                             plot_roc_curve,roc_auc_score,roc_curve)
from sklearn.preprocessing import (OneHotEncoder,LabelEncoder,MinMaxScaler,StandardScaler,)
from sklearn.feature_selection import SelectKBest, chi2
from xgboost import XGBClassifier,XGBRegressor
from catboost import CatBoostClassifier
import warnings
warnings.filterwarnings("ignore")

In [3]:
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer
porter_stemmer = PorterStemmer()
snowball_stemmer = SnowballStemmer(language='english')
nltk.download('punkt')
from nltk.tokenize import word_tokenize
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
stop_words = {"a","an","the"}
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()

def remove_html_tags(raw_html):
  return re.sub(r'<.*?>', '', raw_html)

def remove_urls(raw_text):
    raw_text = re.sub(r'http\S+', '', raw_text)
    return re.sub(r'www\S+', '', raw_text)

def remove_nonalpha(raw_text):
  return re.sub(r'[^a-zA-Z\s]', '', raw_text)

def remove_lines(raw_text):
  return re.sub(r'\n',' ',raw_text)

def lemme_stem_stop(raw_text):
  words = word_tokenize(raw_text)
  final_words=[]
  for word in words:
    word = word.lower()
    if word not in stop_words:
      word = snowball_stemmer.stem(word)
      final_words.append(word)
  return " ".join(final_words)

def pre_processing(raw_text):
  return lemme_stem_stop(remove_lines(remove_nonalpha(remove_urls(remove_html_tags(raw_text)))))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [19]:
df = pd.read_csv("/content/Final.csv")
df = df[df["bias"] != 2]
# text_data = text_df["text"].map(lambda x: pre_processing(x)) 

In [20]:
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer
porter_stemmer = PorterStemmer()
snowball_stemmer = SnowballStemmer(language='english')
nltk.download('punkt')
from nltk.tokenize import word_tokenize
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [21]:
sw = stopwords.words('english')
unwanted = {"he", "him", "his", "himself", "she", "she's", "her", "hers", "herself", "they", "them", "their", "theirs", "themselves"}
sw = [el for el in sw if el not in unwanted]

REPLACE_BY_SPACE_RE = re.compile('[/(){}\[\]\|@,;]')
BAD_SYMBOLS_RE = re.compile('[^0-9a-z #+_]')
STOPWORDS = set(sw)

def clean_text(text):
    """
        text: a string
        
        return: modified initial string
    """
    text = text.lower() # lowercase text
    text = REPLACE_BY_SPACE_RE.sub(' ', text) # replace REPLACE_BY_SPACE_RE symbols by space in text. substitute the matched string in REPLACE_BY_SPACE_RE with space.
    text = BAD_SYMBOLS_RE.sub('', text) # remove symbols which are in BAD_SYMBOLS_RE from text. substitute the matched string in BAD_SYMBOLS_RE with nothing. 
    # text = text.replace('x', '')
#    text = re.sub(r'\W+', '', text)
    text = ' '.join(word for word in text.split() if word not in STOPWORDS) # remove stopwors from text
    return text
df.text = df.text.apply(clean_text)
df.text = df.text.str.replace('\d+', '')

In [22]:
df

Unnamed: 0    id                                               text  bias
0              0     1  besides forests naturally developed forests ma...     0
1              1     2  mother cleans rice separating husk mud particl...     0
2              2     3  free gifts nature things man cannot produce in...     0
3              3     4                humanism concept man measure things     0
4              4     5  various designs clothing found depending count...     0
...          ...   ...                                                ...   ...
1991        1991  1992  mulberry soyabean cotton tobacco flax jinseng ...     1
1993        1993  1994  b self employment picture eradicate widespread...     1
1995        1995  1996  bring ends threads together put knot ends threads     1
1997        1997  1998  potassiumprotein synthesisenables opening clos...     1
1999        1999  2000             game used effectively sports education     1

[1152 rows x 4 columns]

In [15]:
def apply_model(rmf,x,y,isval=False):
    if not isval:
        rmf.fit(x,y)
    y_pred=rmf.predict(x)
    if isval:
        print("\nValidation:")
    else:
        print("\nTrain:")
    print(classification_report(y,y_pred))
    print()
    print(confusion_matrix(y,y_pred))
    print("-"*50)
    return rmf

In [16]:
import gensim.downloader as api
from gensim.models import Word2Vec
w2v = api.load("word2vec-google-news-300")

In [25]:

s_data = df.text.map(lambda x: x.split())

# model_Word2Vec = Word2Vec(sentences=s_data, size=100, window=5, min_count=1, workers=4,batch_words = 2,sg = 0) #sg =1 for skipgram

# train the model
# model_Word2Vec.train(s_data, total_examples=model_Word2Vec.corpus_count, epochs=model_Word2Vec.iter)


def f3(x):
  vec1 = [w2v[word] for word in x if word in w2v.vocab]
  return vec1  

def fn(x):
  vec = f3(x)
  vec = np.array(vec).mean(axis=0)
  return vec

X = s_data.map( lambda x: fn(x))

y = df["bias"]


X_np=[]
for i in X.keys():
  X_np.append(np.array(X[i]))

X_np=np.array(X_np)
X_train_np, X_test_np, y_train, y_test = train_test_split(X_np, y, test_size=0.1, random_state=42,stratify=y)

In [27]:
# from sklearn.feature_extraction.text import CountVectorizer

# vectorizer1 = CountVectorizer()
# X1 = vectorizer1.fit_transform(text_df["text"])
# y = text_df["bias"]
# X_train, X_test, y_train, y_test = train_test_split(X1, y, test_size=0.1, random_state=42,stratify=y)

rmf = CatBoostClassifier(iterations=50,verbose=0)
rmf=apply_model(rmf,X_train_np,y_train)
rmf=apply_model(rmf,X_test_np,y_test,isval=True)


Train:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       496
           1       1.00      1.00      1.00       540

    accuracy                           1.00      1036
   macro avg       1.00      1.00      1.00      1036
weighted avg       1.00      1.00      1.00      1036


[[496   0]
 [  2 538]]
--------------------------------------------------

Validation:
              precision    recall  f1-score   support

           0       0.88      0.78      0.83        55
           1       0.82      0.90      0.86        61

    accuracy                           0.84       116
   macro avg       0.85      0.84      0.84       116
weighted avg       0.85      0.84      0.84       116


[[43 12]
 [ 6 55]]
--------------------------------------------------


In [28]:
# Hyperparameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
  
param_grid = {'learning_rate': [0.1, 0.01, 0.02,0.04], 
              'depth': list(range(4,11))}


  
grid = GridSearchCV(rmf, param_grid, refit = True, verbose = 3)


# fitting the model for grid search
grid.fit(X_np,y)

print(grid.best_params_)

rmf_best = grid.best_estimator_

Fitting 5 folds for each of 28 candidates, totalling 140 fits
[CV 1/5] END ........depth=4, learning_rate=0.1;, score=0.840 total time=   1.7s
[CV 2/5] END ........depth=4, learning_rate=0.1;, score=0.840 total time=   1.7s
[CV 3/5] END ........depth=4, learning_rate=0.1;, score=0.830 total time=   2.8s
[CV 4/5] END ........depth=4, learning_rate=0.1;, score=0.848 total time=   1.8s
[CV 5/5] END ........depth=4, learning_rate=0.1;, score=0.878 total time=   1.6s
[CV 1/5] END .......depth=4, learning_rate=0.01;, score=0.775 total time=   1.6s
[CV 2/5] END .......depth=4, learning_rate=0.01;, score=0.814 total time=   1.8s
[CV 3/5] END .......depth=4, learning_rate=0.01;, score=0.796 total time=   1.7s
[CV 4/5] END .......depth=4, learning_rate=0.01;, score=0.791 total time=   1.6s
[CV 5/5] END .......depth=4, learning_rate=0.01;, score=0.822 total time=   1.7s
[CV 1/5] END .......depth=4, learning_rate=0.02;, score=0.797 total time=   1.7s
[CV 2/5] END .......depth=4, learning_rate=0.02

In [29]:
model=apply_model(rmf_best,X_test_np,y_test,isval=True)


Validation:
              precision    recall  f1-score   support

           0       0.96      0.93      0.94        55
           1       0.94      0.97      0.95        61

    accuracy                           0.95       116
   macro avg       0.95      0.95      0.95       116
weighted avg       0.95      0.95      0.95       116


[[51  4]
 [ 2 59]]
--------------------------------------------------


In [30]:
grid.best_params_

{'depth': 5, 'learning_rate': 0.1}

In [31]:
model_best = apply_model(rmf_best,X_np,y)


Train:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       551
           1       0.98      0.96      0.97       601

    accuracy                           0.97      1152
   macro avg       0.97      0.97      0.97      1152
weighted avg       0.97      0.97      0.97      1152


[[538  13]
 [ 25 576]]
--------------------------------------------------


In [32]:
y_hat = model_best.predict(X_np)
len(y_hat)

1152

In [33]:
try:
  text_df = df.drop('Unnamed: 0',axis=1)
  text_df = text_df.set_index('id')
except:
  pass
text_df

text  bias
id                                                           
1     besides forests naturally developed forests ma...     0
2     mother cleans rice separating husk mud particl...     0
3     free gifts nature things man cannot produce in...     0
4                   humanism concept man measure things     0
5     various designs clothing found depending count...     0
...                                                 ...   ...
1992  mulberry soyabean cotton tobacco flax jinseng ...     1
1994  b self employment picture eradicate widespread...     1
1996  bring ends threads together put knot ends threads     1
1998  potassiumprotein synthesisenables opening clos...     1
2000             game used effectively sports education     1

[1152 rows x 2 columns]

In [34]:
text_df['pred'] = y_hat
text_df

text  bias  pred
id                                                                 
1     besides forests naturally developed forests ma...     0     1
2     mother cleans rice separating husk mud particl...     0     0
3     free gifts nature things man cannot produce in...     0     0
4                   humanism concept man measure things     0     0
5     various designs clothing found depending count...     0     0
...                                                 ...   ...   ...
1992  mulberry soyabean cotton tobacco flax jinseng ...     1     1
1994  b self employment picture eradicate widespread...     1     1
1996  bring ends threads together put knot ends threads     1     1
1998  potassiumprotein synthesisenables opening clos...     1     1
2000             game used effectively sports education     1     1

[1152 rows x 3 columns]

In [35]:
pair_df = pd.read_csv('/content/pairs.txt',names=['p1','p2','label'])
pair_df

p1    p2  label
0         98   651      0
1        696  1870      1
2       1073  1620      0
3        167   633      0
4          4   640      0
...      ...   ...    ...
155946   546  1512      1
155947   720  1902      1
155948  1112  1591      0
155949   396  1472      1
155950  1021  1680      0

[155951 rows x 3 columns]

In [36]:

pred_label = []
for i in range(pair_df.shape[0]):
    pred_label.append(np.logical_xor(text_df.pred[pair_df.p1[i]],text_df.pred[pair_df.p2[i]]).astype(int))

In [37]:
print(classification_report(pair_df.label,pred_label))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94     80400
           1       0.92      0.94      0.93     75551

    accuracy                           0.93    155951
   macro avg       0.93      0.94      0.93    155951
weighted avg       0.94      0.93      0.93    155951



In [38]:
print(confusion_matrix(pair_df.label,pred_label))

[[74428  5972]
 [ 4196 71355]]


In [39]:
text_df[text_df.bias!=text_df.pred]

text  bias  pred
id                                                                 
1     besides forests naturally developed forests ma...     0     1
88    well ahead festival people clean their houses ...     0     1
136   etc cause communicable parasitic bacteria prot...     0     1
338       mother store rice bengal gram jowar wheat etc     0     1
368   mixing chemicals dust micro organisms harmful ...     0     1
440   he change form shape place material given natu...     0     1
504   mla constituency tolpatti serious shortage wat...     0     1
545   many things around us occur naturally mixtures...     0     1
579   contribution photosynthesis human civilization...     0     1
585   though bangladesh adequate manpower her worker...     0     1
588               anitha mother mixed jeera wheat flour     0     1
620   ampere named andr marie amp french mathematici...     0     1
631   copper sulphate crystals often include water c...     0     1
1006  four months back mallaiah borrowed rs chandula...     1     0
1022      he says solid players stand near cards solids     1     0
1047                 important them sargeant commission     1     0
1077  eg tallness dwarfness tt tt red flower white f...     1     0
1081  kunwar sing nana saheb consequences though str...     1     0
1138  sometimes megaliths contain one skeleton indic...     1     0
1196    he hero hundred battles bore scars war his body     1     0
1504  hands cooperation sympathy extended automatica...     1     0
1505  works painting services nursing sake earning m...     1     0
1506  school textbooks glorified french justified co...     1     0
1543  achievements indian kabaddi team international...     1     0
1555  pulakeshi ii could rule whole his kingdom one ...     1     0
1557  he undertook ambitious military expedition con...     1     0
1571                     two his sons help him his work     1     0
1601           man got car tried pluck weaver bird nest     1     0
1614  he stayed island named lesbos five years conti...     1     0
1618  power observing thinking remembering thirst kn...     1     0
1619  step inhale dwipada prasanasana dandasana exte...     1     0
1674  telangana landlordism armed peasant rebellion ...     1     0
1675  her teacher matilda lyngdoh responds her quest...     1     0
1686                        family husband two children     1     0
1724  men women increase their income self employed ...     1     0
1748  mayur varma he brahmin kanchi his higher educa...     1     0
1920       l search food l caring protecting their race     1     0
1968  firstly shanti given copy chargesheet evidence...     1     0

In [40]:
model.save_model('word2vec-G-catboost')

In [41]:
del model

In [42]:
del grid
